// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvv6SFsCFAMQluSSMj1dSvdM5bNiO6PZo',
    appId: '1:654980044364:web:a1ee5962e6a3def7c606e9',
    messagingSenderId: '654980044364',
    projectId: 'habitsync-92ecc',
    authDomain: 'habitsync-92ecc.firebaseapp.com',
    storageBucket: 'habitsync-92ecc.firebasestorage.app',
    measurementId: 'G-78P5V0SD4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6U6ke_EwVpT_9NFuc0ltvQAwc4wAxOz0',
    appId: '1:654980044364:android:a7ff032e439fd97cc606e9',
    messagingSenderId: '654980044364',
    projectId: 'habitsync-92ecc',
    storageBucket: 'habitsync-92ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBysdE1vFcnaUKjKHVff2vPPbJ7PwOlA8',
    appId: '1:654980044364:ios:56b117afd39558d7c606e9',
    messagingSenderId: '654980044364',
    projectId: 'habitsync-92ecc',
    storageBucket: 'habitsync-92ecc.firebasestorage.app',
    iosBundleId: 'com.example.habitSync',
  );
}
